name: Build website
runs:
  using: composite
  steps:
    - name: Set up Python 3.14
      uses: actions/setup-python@v6
      with:
        python-version: '3.14'
        cache: 'pip'

    - name: Install dependencies
      shell: bash
      run: |
        pip install -r requirements.txt --upgrade

    - name: Build website
      shell: bash
      run: |
        nikola build -a
